version: '3.8'
services:
  hr-monitor-ble-server:
    build:
      context: .
    container_name: hr-monitor-ble-server
    restart: unless-stopped
    environment:
      - ENV=${ENV}
      - KAFKA_BROKER=${KAFKA_BROKER}
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
    env_file:
      - .env
    networks:
      - kafka-net

  kafka-consumer:
    build:
      context: .
      dockerfile: ./pkg/kafka/Dockerfile.consumer
    container_name: kafka-consumer
    restart: unless-stopped
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - TOPIC=${TOPIC}
    env_file:
      - .env
    networks:
      - kafka-net

networks:
  kafka-net:
