// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/heartrate.proto

package heartratepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HeartRateMeasurement is a single heart rate notification, mirroring the
// BLE Heart Rate Measurement characteristic (GATT 0x2A37).
type HeartRateMeasurement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instantaneous heart rate in beats per minute.
	HeartRate uint32 `protobuf:"varint,1,opt,name=heart_rate,json=heartRate,proto3" json:"heart_rate,omitempty"`
	// RR intervals between heartbeats, in milliseconds. May be empty.
	RrIntervals []uint32 `protobuf:"varint,2,rep,packed,name=rr_intervals,json=rrIntervals,proto3" json:"rr_intervals,omitempty"`
	// Time the measurement was received by the server (UTC).
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Which strap produced this reading, e.g. "polar-h10" or "charge-6". Lets two
	// gateways publish to one topic without their beats being indistinguishable —
	// consumers that predate this field simply ignore it.
	Source        string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartRateMeasurement) Reset() {
	*x = HeartRateMeasurement{}
	mi := &file_proto_heartrate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartRateMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartRateMeasurement) ProtoMessage() {}

func (x *HeartRateMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heartrate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartRateMeasurement.ProtoReflect.Descriptor instead.
func (*HeartRateMeasurement) Descriptor() ([]byte, []int) {
	return file_proto_heartrate_proto_rawDescGZIP(), []int{0}
}

func (x *HeartRateMeasurement) GetHeartRate() uint32 {
	if x != nil {
		return x.HeartRate
	}
	return 0
}

func (x *HeartRateMeasurement) GetRrIntervals() []uint32 {
	if x != nil {
		return x.RrIntervals
	}
	return nil
}

func (x *HeartRateMeasurement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartRateMeasurement) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_proto_heartrate_proto protoreflect.FileDescriptor

const file_proto_heartrate_proto_rawDesc = "" +
	"\n" +
	"\x15proto/heartrate.proto\x12\fheartrate.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\x14HeartRateMeasurement\x12\x1d\n" +
	"\n" +
	"heart_rate\x18\x01 \x01(\rR\theartRate\x12!\n" +
	"\frr_intervals\x18\x02 \x03(\rR\vrrIntervals\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06sourceBDZBgithub.com/clunc/hr-monitor-ble-server/pkg/heartratepb;heartratepbb\x06proto3"

var (
	file_proto_heartrate_proto_rawDescOnce sync.Once
	file_proto_heartrate_proto_rawDescData []byte
)

func file_proto_heartrate_proto_rawDescGZIP() []byte {
	file_proto_heartrate_proto_rawDescOnce.Do(func() {
		file_proto_heartrate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_heartrate_proto_rawDesc), len(file_proto_heartrate_proto_rawDesc)))
	})
	return file_proto_heartrate_proto_rawDescData
}

var file_proto_heartrate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_heartrate_proto_goTypes = []any{
	(*HeartRateMeasurement)(nil),  // 0: heartrate.v1.HeartRateMeasurement
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_heartrate_proto_depIdxs = []int32{
	1, // 0: heartrate.v1.HeartRateMeasurement.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_heartrate_proto_init() }
func file_proto_heartrate_proto_init() {
	if File_proto_heartrate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_heartrate_proto_rawDesc), len(file_proto_heartrate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_heartrate_proto_goTypes,
		DependencyIndexes: file_proto_heartrate_proto_depIdxs,
		MessageInfos:      file_proto_heartrate_proto_msgTypes,
	}.Build()
	File_proto_heartrate_proto = out.File
	file_proto_heartrate_proto_goTypes = nil
	file_proto_heartrate_proto_depIdxs = nil
}
